import { Editor } from "@monaco-editor/react";
import React, { useState, useEffect } from "react";

const Code = ({
  code,
  setCode,
  output,
  consoleLogs,
  handleRunCode,
  activeSection,
  setPreviewUrl,
  previewUrl,
}: any) => {
  const [activeFile, setActiveFile] = useState<string>("frontend.jsx");
  const [isFullScreen, setIsFullScreen] = useState(false);
  const [files, setFiles] = useState<any>({
    "frontend.jsx": `// Frontend React Component
import React, { useState } from 'react';

const App = () => {
  const [count, setCount] = useState(0);

  return (
    <div className="p-6">
      <h1 className="text-2xl font-bold text-white">Hello Cobra AI!</h1>
      <p className="text-gray-300">Count: {count}</p>
      <button 
        className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded mt-4"
        onClick={() => setCount(count + 1)}
      >
        Increment
      </button>
    </div>
  );
};

export default App;`,

    "backend.js": `// Backend Express Server
const express = require('express');
const cors = require('cors');

const app = express();
const PORT = 3000;

// Middleware
app.use(cors());
app.use(express.json());

// Routes
app.get('/', (req, res) => {
  res.json({ message: 'Hello from Cobra AI Backend!' });
});

app.get('/api/users', (req, res) => {
  res.json([
    { id: 1, name: 'John Doe', email: 'john@example.com' },
    { id: 2, name: 'Jane Smith', email: 'jane@example.com' }
  ]);
});

// Start server
app.listen(PORT, () => {
  console.log(\`🚀 Server running on port \${PORT}\`);
});`,

    "package.json": `{
  "name": "cobra-ai-project",
  "version": "1.0.0",
  "description": "A full-stack project generated by Cobra AI",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "start": "node backend.js"
  },
  "dependencies": {
    "express": "^4.18.2",
    "cors": "^2.8.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "vite": "^4.4.5",
    "@vitejs/plugin-react": "^4.0.3"
  }
}`,
  });

  const editorOptions: any = {
    minimap: { enabled: false },
    fontSize: 13,
    wordWrap: "on",
    automaticLayout: true,
    tabSize: 2,
    scrollBeyondLastLine: false,
    padding: { top: 16 },
    lineNumbersMinChars: 3,
    folding: false,
    touchSupported: true,
    renderLineHighlight: "all",
  };

  // Initialize code with active file content on mount
  useEffect(() => {
    setCode(files[activeFile]);
  }, []); // Empty dependency array - only run once on mount

  // Handle external code updates (from test button)
  useEffect(() => {
    if (code && code !== files[activeFile]) {
      // Determine which file should receive the code based on content
      const targetFile = determineTargetFile(code);

      if (targetFile !== activeFile) {
        // Switch to the appropriate file tab
        setActiveFile(targetFile);
      }

      // Update the file content
      setFiles((prev: any) => ({
        ...prev,
        [targetFile]: code,
      }));
    }
  }, [code]); // Only run when code prop changes

  const determineTargetFile = (code: string): string => {
    // Check if it's JSX code (contains JSX syntax)
    const isJSX =
      code.includes("</") ||
      code.includes("/>") ||
      code.includes("className=") ||
      (code.includes("return (") && code.includes("</")) ||
      code.includes("React") ||
      code.includes("useState") ||
      code.includes("useEffect");

    // Check if it's backend code (contains Express/Node.js patterns)
    const isBackend =
      code.includes("require(") ||
      code.includes("express") ||
      code.includes("app.listen") ||
      code.includes("app.get") ||
      code.includes("app.post") ||
      code.includes("module.exports") ||
      code.includes("res.json") ||
      code.includes("res.send");

    if (isJSX && !isBackend) {
      return "frontend.jsx";
    } else if (isBackend) {
      return "backend.js";
    } else {
      // Default to frontend for generic JavaScript
      return "frontend.jsx";
    }
  };

  const getLanguage = (filename: string) => {
    if (filename.endsWith(".jsx")) return "javascript";
    if (filename.endsWith(".js")) return "javascript";
    if (filename.endsWith(".json")) return "json";
    return "javascript";
  };

  const handleFileChange = (value: string | undefined) => {
    if (value !== undefined) {
      const updatedFiles = {
        ...files,
        [activeFile]: value,
      };
      setFiles(updatedFiles);
      // Update the main code state when user edits the file
      setCode(value);
    }
  };

  const handleFileSwitch = (filename: string) => {
    setActiveFile(filename);
    // Update the main code state with the new file's content
    setCode(files[filename]);
  };

  const toggleFullScreen = () => {
    setIsFullScreen(!isFullScreen);
  };

  // Close full screen when active section changes
  useEffect(() => {
    if (activeSection !== "code") {
      setIsFullScreen(false);
    }
  }, [activeSection]);

  return (
    <>
      {/* Full Screen Preview Overlay */}
      {isFullScreen && previewUrl && (
        <div className="fixed inset-0 z-50 bg-black bg-opacity-90 flex flex-col">
          {/* Full Screen Header */}
          <div className="flex items-center justify-between p-4 bg-gray-900 border-b border-red-500/20">
            <h2 className="text-xl font-bold text-white">
              🔍 Preview - Full Screen
            </h2>
            <div className="flex items-center gap-3">
              <button
                onClick={toggleFullScreen}
                className="bg-red-600 hover:bg-red-700 text-white font-semibold px-4 py-2 rounded-xl transition-all duration-300"
              >
                ✕ Exit Full Screen
              </button>
            </div>
          </div>

          {/* Full Screen Preview */}
          <div className="flex-1 w-full h-full">
            <iframe
              src={previewUrl}
              className="w-full h-full border-0"
              title="Full Screen Preview"
              sandbox="allow-scripts allow-same-origin"
            />
          </div>
        </div>
      )}

      <div
        className={`${
          activeSection === "code" ? "block" : "hidden"
        } lg:block h-[calc(100vh-180px)] lg:h-full`}
      >
        <div className="bg-gray-900/80 backdrop-blur-xl rounded-2xl border border-red-500/20 h-full flex flex-col">
          {/* Editor Header */}
          <div className="p-4 border-b border-red-500/20">
            <div className="flex items-center justify-between">
              <h2 className="text-xl font-bold text-white">💻 Code Editor</h2>
              <div className="flex items-center gap-3">
                {/* Full Screen Toggle Button */}
                {previewUrl && (
                  <button
                    onClick={toggleFullScreen}
                    className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold px-4 py-2 rounded-xl transition-all duration-300"
                    title="Toggle Full Screen Preview"
                  >
                    <svg
                      className="w-4 h-4"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4"
                      />
                    </svg>
                    Full Screen
                  </button>
                )}

                {/* Run Code Button */}
                <button
                  onClick={() => {
                    handleRunCode({ files });
                  }}
                  className="bg-gradient-to-r from-emerald-600 to-green-500 hover:from-emerald-700 hover:to-green-600 text-white font-semibold px-4 lg:px-6 py-2 rounded-xl transition-all duration-300 hover:shadow-[0_0_15px_rgba(16,185,129,0.5)] text-sm lg:text-base cursor-pointer"
                >
                  🚀 Run Code
                </button>
              </div>
            </div>
          </div>

          {/* File Tabs */}
          <div className="flex border-b border-red-500/20 bg-gray-800/50">
            {Object.keys(files).map((filename) => (
              <button
                key={filename}
                onClick={() => handleFileSwitch(filename)}
                className={`px-4 py-3 text-sm font-medium border-b-2 transition-all duration-200 ${
                  activeFile === filename
                    ? "border-emerald-500 text-emerald-400 bg-gray-900/50"
                    : "border-transparent text-gray-400 hover:text-gray-300 hover:bg-gray-700/50"
                }`}
              >
                {filename}
              </button>
            ))}
          </div>

          {/* Monaco Editor - Fixed Height */}
          <div
            className="flex-1"
            style={{ minHeight: "300px", maxHeight: "60vh" }}
          >
            <Editor
              height="100%"
              language={getLanguage(activeFile)}
              value={files[activeFile]}
              onChange={handleFileChange}
              theme="vs-dark"
              options={editorOptions}
            />
          </div>

          {/* Preview & Output Side by Side - Fixed Height */}
          <div
            className="border-t border-red-500/20"
            style={{ maxHeight: "30vh", minHeight: "150px" }}
          >
            <div className="grid grid-cols-2 h-full divide-x divide-red-500/20">
              {/* Preview Section */}
              <div className="flex flex-col h-full">
                <div className="flex items-center justify-between p-3 bg-gray-800/50 border-b border-red-500/20">
                  <h3 className="text-white font-semibold text-sm">
                    Live Preview
                  </h3>
                  {previewUrl && (
                    <button
                      onClick={toggleFullScreen}
                      className="text-blue-400 hover:text-blue-300 text-xs flex items-center gap-1"
                    >
                      <svg
                        className="w-3 h-3"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4"
                        />
                      </svg>
                      Full Screen
                    </button>
                  )}
                </div>
                <div className="flex-1 bg-black p-2 overflow-hidden">
                  {previewUrl ? (
                    <iframe
                      src={previewUrl}
                      className="w-full h-full rounded border border-gray-700"
                      title="Code Preview"
                      sandbox="allow-scripts allow-same-origin"
                    />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center text-gray-500 text-sm">
                      Run code to see preview
                    </div>
                  )}
                </div>
              </div>

              {/* Output Section */}
              <div className="flex flex-col h-full">
                <div className="flex items-center justify-between p-3 bg-gray-800/50 border-b border-red-500/20">
                  <h3 className="text-white font-semibold text-sm">
                    Console Output
                  </h3>
                </div>
                <div className="flex-1 bg-gray-950 p-3 overflow-auto">
                  <div className="text-green-400 font-mono text-xs whitespace-pre-wrap h-full">
                    {output || "// Run your code to see output here"}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Code;
